### PR TITLE
Fix platform width and minimum width

### LINKED ISSUE #7: Platform width

### PR DESCRIPTION
**Pull request by StephanieBekker**
Fix #7

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -76,7 +76,7 @@ function resetGame() {
 
     // The first platform is always the same
     // x + w has to match paddingX
-    platforms = [{ x: 50, w: 50 }];
+    platforms = [{ x: 50, w: 80 }];
```
Comment (moon2300) [inline script.js:79]:
```suggestion
    platforms = [{ x: 50, w: 90 }];
```

**Review by moon2300 — APPROVED** [review]
